# Generated by Django 4.2.1 on 2023-07-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to='F:\\Samad\\Code\\Code Projects\\Py\\Online_Shop\\online/media/images/'),
        ),
    ]
