# Generated by Django 4.2.1 on 2023-07-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usercreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
